// Copyright 2022 Alexander Mandera (@AlexanderMandera)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define SERIAL_PIO_USE_PIO1
#define WS2812_PIO_USE_PIO1

#define SPLIT_HAND_PIN GP22

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP15     // USART TX pin
#define SERIAL_USART_RX_PIN GP14     // USART RX pin
//#define SPLIT_TRANSPORT_MIRROR

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

// LED Config

#ifdef RGB_MATRIX_ENABLE

#define ENABLE_RGB_MATRIX_HUE_BREATHING
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_HUE_BREATHING

#define RGB_DI_PIN GP21
#define DRIVER_LED_TOTAL 76
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120
#define RGB_MATRIX_STARTUP_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_LED_COUNT 76
#define RGB_DISABLE_WHEN_USB_SUSPENDED

#endif